### ISSUE TITLE
Non-editable fields on home page

### ISSUE THREAD

**Issue by natalie4pfoods** [ocupop/4p-website#111]
**Is your feature request related to a problem? Please describe.**
I can't edit some of the fields I'd like to be able to on the home page (through Cloud Cannon).

**Describe the solution you'd like**
Please make them editable, or let me know if that's not possible. The fields I'd like to edit are:
- stories of satisfied customers
- the block of text below the "food access programs" header (see screenshot below)

**Describe alternatives you've considered**

**Additional context**
[![Screenshot from Gyazo](https://gyazo.com/3b13e17af4770460605d279071eaafc6/raw)](https://gyazo.com/3b13e17af4770460605d279071eaafc6)

**Comment by tbeck** [comment]
@jonathanwburr - Just adding you here to prioritize these updates.

**Comment by jonathanwburr** [comment]
commit 8d82369
