### ISSUE TITLE
Firestore Emulator Seeding

### ISSUE THREAD

**Issue by cdnicoll** [ocupop/4p-website#119]
Locally we should be able to spin up the emulator and optionally seed data.

Currently we have to run the following commands to get this to work:
```
# seed db
firebase emulators:start --only firestore
node ./src/common/data/seedData --seed

# export
firebase emulators:export ./

# import
firebase emulators:start --import ./
```

The problem is around firestore triggers firing when we try to seed. Currently doing the above will create a `firestore-export` directory which will be imported. Is this something we want to commit to our repo or have locally...

**Comment by cdnicoll** [comment]
@tbeck we can probably put this in the ice box based off our conversations the other day

**Comment by tbeck** [comment]
Closing...
