### ISSUE TITLE
Home page titles don’t show up on home page

### ISSUE THREAD

**Issue by julieysandler** [ocupop/4p-website#187]
Page title does not show up on the Tab for Home even though meta data and CMS page has page titles entered. This issue does not seem to duplicate on the subsequent pages that I have experience thus far.

![Screen Shot 2022-08-18 at 11 56 41 AM](https://user-images.githubusercontent.com/108093359/185440775-81ea5518-2e05-4fd0-8d06-a01b87a6986e.png)
 page. 

![Screen Shot 2022-08-18 at 11 57 23 AM](https://user-images.githubusercontent.com/108093359/185440683-cd2ef0b8-b366-40bd-9c0c-6d14cdc73942.png)

![Screen Shot 2022-08-18 at 11 57 27 AM](https://user-images.githubusercontent.com/108093359/185440802-198a029d-9e83-447b-a27d-609766315b85.png)

**Comment by jhamlett** [comment]
Fixed.
