### ISSUE TITLE
Recipes stop at page 1

### ISSUE THREAD

**Issue by julieysandler** [ocupop/4p-website#188]
Recipe page does not continue on and is limiting the number of recipes displayed.
Needs to be updated to publish all recipes and update pagination.
![Screen Shot 2022-08-18 at 12 00 41 PM](https://user-images.githubusercontent.com/108093359/185441199-955ba501-42f6-4903-8127-d99f54fda9b8.png)

**Comment by jhamlett** [comment]
This was fixed with an Algolia sync.
