### ISSUE TITLE
Recipe Feature Image is not displaying on Recipe Cards on Recipe Page

### ISSUE THREAD

**Issue by julieysandler** [ocupop/4p-website#189]
Recipe feature image is not displaying updated Featured Image on Recipe page, but is displaying accurately on cards featured on the home page.
![Screen Shot 2022-08-18 at 12 02 11 PM](https://user-images.githubusercontent.com/108093359/185441552-5a98ca04-18d0-46f3-822c-e5a5655c466a.png)
![Screen Shot 2022-08-18 at 12 02 27 PM](https://user-images.githubusercontent.com/108093359/185441559-82d7e54a-4d0e-4a29-9673-dc7a14927c19.png)

**Comment by jhamlett** [comment]
This was fixed with an Algolia sync
