### ISSUE TITLE
Update all header section to allow for formatting

### ISSUE THREAD

**Issue by julieysandler** [ocupop/4p-website#191]
Currently - there are several places throughout the site where we cannot adjust the format settings for Headers and Subheaders 

**Very limited formatting options available:**
![Screen Shot 2022-08-18 at 12 04 52 PM](https://user-images.githubusercontent.com/108093359/185442377-ba237aac-3d9c-481d-a1fe-6ee80ff090f5.png)

**Full suite of formatting options available:**
![Screen Shot 2022-08-18 at 12 04 58 PM](https://user-images.githubusercontent.com/108093359/185442435-fb76e4c3-2248-43b0-a470-11a532a3c2d4.png)

Can we adjust this?

**Comment by jhamlett** [comment]
I went through page by page and adjusted these. Formerly headings had editable options but you could not change the heading size itself. Now the headings are all inside editable containers and you can freely changes h2s to h3s or however you would like to adjust.
