### ISSUE TITLE
Reformat H1-H5 Heading Settings to updated style guide

### ISSUE THREAD

**Issue by julieysandler** [ocupop/4p-website#192]
All Heading levels are set to ALL CAPS, which makes it hard to set headers up throughout the site without it shouting at you.

Without being able to add Heading levels to paragraph titles, etc, makes it hard to update for SEO purposes.

Can we change all fonts to reflect this style guide:
![Screen Shot 2022-08-18 at 12 17 17 PM](https://user-images.githubusercontent.com/108093359/185444510-1a63e56a-1fcf-4cf2-aff0-6a7dc2af3b84.png)

**Comment by jhamlett** [comment]
These css styles were all updated to match the style guide. There are quite a few instances where headings will need to be adjusted now, there are headings with some inline styles, headings that were keyed in as all lowercase, headings wrapped in <em> tags, etc... You may want to go through page by page and adjust to your liking.

**Comment by julieysandler** [comment]
Thank you!

It doesn't appear that the "Normal" setting was adjusted to the Spectral Regular. Would that be possible? (Or, Georgia if Spectral is not available)?

I've also gone in and adjusted headers and found a few instances where the formatting was not available. I've linked those areas below with screenshots of the content that does not have formatting available for H1 settings.

How To Shop: https://4pfoods.com/how-to-shop
![Screen Shot 2022-09-06 at 4 07 14 PM](https://user-images.githubusercontent.com/108093359/188908929-d383eb5d-2d32-4adf-8719-d019bc982a73.png)

Our Impact: https://4pfoods.com/our-impact
![Screen Shot 2022-09-06 at 4 27 54 PM](https://user-images.githubusercontent.com/108093359/188912544-e46af50c-515c-4222-a577-bcbc14ed9768.png)

About Us: https://4pfoods.com/about
![Screen Shot 2022-09-06 at 10 27 13 AM](https://user-images.githubusercontent.com/108093359/188912832-e43a6383-af41-4747-9e09-2b49d3899ebf.png)

How it Works: https://4pfoods.com/how-it-works
"Our Favorites" 
![Screen Shot 2022-09-07 at 10 46 22 AM](https://user-images.githubusercontent.com/108093359/188913913-f4485d29-b306-4de9-b071-e683d548cc76.png)

Referral Programs: https://4pfoods.com/referral-programs
![Screen Shot 2022-09-07 at 9 49 39 AM](https://user-images.githubusercontent.com/108093359/188914095-c6de62e6-23f5-4875-96d3-cc64dd2bb82b.png)
- I don't think we need this title here - it feels random.

And this screenshot I took - but can no longer find where it lives If you happen to come across it.
![Screen Shot 2022-09-06 at 3 54 25 PM](https://user-images.githubusercontent.com/108093359/188914284-e42c5c21-b549-4bd8-a336-70ad82fe9d82.png)

**Comment by jhamlett** [comment]
These should all be updated in staging.
