### ISSUE TITLE
Need access to image/header edits on specific pages 

### ISSUE THREAD

**Issue by julieysandler** [ocupop/4p-website#194]
These are places I cannot access/edit images or text:

**On the home page**
Cannot edit/access icons
![Screen Shot 2022-08-18 at 12 28 09 PM](https://user-images.githubusercontent.com/108093359/185446953-2b92195b-140d-4956-87c0-9190348b2b24.png)

Cannot edit/access icons
![Screen Shot 2022-08-18 at 12 29 05 PM](https://user-images.githubusercontent.com/108093359/185446987-566481f7-c077-40ae-8f39-ab3debd9e8dc.png)

Cannot edit header
![Screen Shot 2022-08-18 at 12 29 09 PM](https://user-images.githubusercontent.com/108093359/185447005-3e2df8ad-c6bc-451e-900a-98124f02490a.png)

**On How it Works**
Cannot edit/access icons
![Screen Shot 2022-08-18 at 12 31 45 PM](https://user-images.githubusercontent.com/108093359/185447354-7a6fb984-81c8-40c3-9e36-ef2e4d00ec09.png)

**Comment by jhamlett** [comment]
Should be access to editing on all of these now.
